import { useState } from "react";
import { Link } from "react-router-dom";
import "../landing.css";

export function Brand() { return <span className="brand"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>modus<span className="brand-divider"/> <span className="brand-product">Document checks</span></span>; }

export default function Landing() {
  const [scenario, setScenario] = useState(0);
  const [menu, setMenu] = useState(false);
  const scenarios = [
    { name: "Invoice revised", source: "Invoice · INV-2025-1015", change: "$12,500 → $12,750", affected: 1, rules: 9, caption: "A new invoice amount needs another look.", target: "Invoice vs. accounting record", result: "$250 difference to investigate" },
    { name: "Shared document", source: "Bank statement · June 2025", change: "Supporting document changed", affected: 20, rules: 180, caption: "One bank statement can support many checks.", target: "20 related items", result: "Check the payment details again" },
    { name: "Earlier approval", source: "Approval memo · AP-1015", change: "Evidence revised after review", affected: 1, rules: 9, caption: "An earlier approval may need checking again.", target: "An item approved earlier", result: "Review the supporting document again" },
  ];
  const s = scenarios[scenario];
  return <div className="modus-site">
    <div className="announcement">An independent product concept for Modus <span>•</span> Try it with sample records <a href="#research">Read the rationale ↗</a></div>
    <header className="site-nav"><Link to="/" aria-label="Document checks home"><Brand/></Link><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>☰</button><nav className={menu ? "nav-links open" : "nav-links"}><a href="#advantage" onClick={()=>setMenu(false)}>What it does</a><a href="#how-it-works" onClick={()=>setMenu(false)}>How it works</a><Link to="/about-demo">Simple guide</Link><Link className="button button-blue" to="/dashboard">Open the demo <span>↗</span></Link></nav></header>
    <main>
      <section className="landing-hero">
        <div className="architectural-grid" aria-hidden="true"/>
        <div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> CHECK THE DOCUMENTS. UNDERSTAND THE NUMBERS.</p><h1>A document changes.<br/>Know what to <em>check next.</em></h1><p className="hero-description">Compare invoices with accounting records. Find different amounts or missing documents. When a document changes, see which earlier checks may need another look.</p><div className="hero-actions"><Link className="button button-blue" to="/dashboard">Try the demo <span>↗</span></Link><a className="text-link" href="#interactive-demo"><span className="play-icon">▷</span> See it in action</a></div><p className="hero-note">Independent project · Sample audit workspace · A person makes the final decision</p><Link className="text-link" to="/receipts">Have a receipt? Upload it and read the details ↗</Link></div>
        <div className="hero-visual" aria-label="Illustrative evidence dependency graph"><div className="visual-topline"><span className="live-dot"/> WHEN A DOCUMENT CHANGES <span className="visual-live">ILLUSTRATION</span></div><div className="graph-source"><span className="file-icon">≡</span><div><small>SOURCE DOCUMENT · V2</small><strong>Invoice INV-2025-1015</strong><span>Revised total <b>$12,750.00</b></span></div><span className="small-tag">Changed</span></div><div className="graph-stem"/><div className="graph-middle"><span>RELATED ITEMS FOUND</span><i/></div><div className="graph-branches"><div className="graph-node"><span className="node-icon">⌘</span><small>ITEM TO CHECK</small><strong>Invoice vs. accounting record</strong><span className="amber-text">Review required ↗</span></div><div className="graph-node muted-node"><span className="node-icon">✓</span><small>OTHER ITEMS</small><strong>No link to this document</strong><span>Earlier results stay the same</span></div></div><div className="visual-bottom"><span><i className="amber-dot"/> See what needs another look.</span><span>01 → 09</span></div></div>
      </section>
      <div className="blue-ribbon"><span>DOCUMENTS, NUMBERS, AND THE CHECKS BETWEEN THEM</span><p>From “what changed?” to <strong>“what needs my attention?”</strong></p><a href="#how-it-works" aria-label="Explore the workflow">↓</a></div>
      <section className="section advantage" id="advantage"><div className="section-heading"><p className="eyebrow">THE OPPORTUNITY</p><h2>Every number needs<br/><em>a document behind it.</em></h2><p>A corrected invoice. A new bank statement. A late approval.<br/>The work doesn’t end when evidence first arrives.</p></div><div className="feature-grid">{[{n:"01",title:"See what uses a document",text:"See which items were checked using an invoice, bank statement, or approval note, and whether someone already approved them."},{n:"02",title:"Know where to look again",text:"If an invoice changes, find the items that use it. Other items keep their existing results."},{n:"03",title:"Understand earlier decisions",text:"Find older document versions and download a report to help a person decide what needs checking again."}].map(f=><article key={f.n}><span className="feature-number">{f.n}</span><h3>{f.title}</h3><p>{f.text}</p><span className="feature-end" aria-hidden="true">↗</span></article>)}</div></section>
      <section className="section demo-section" id="interactive-demo"><div className="section-heading horizontal"><div><p className="eyebrow">EXPLORE THE CONCEPT</p><h2>One change.<br/><em>Every connection.</em></h2></div><p>Pick an example to see what a change could affect.<br/>These examples use made-up numbers.</p></div><div className="demo-workbench"><div className="demo-tabs" role="tablist" aria-label="Example scenarios">{scenarios.map((item,i)=><button key={item.name} id={`scenario-${i}`} role="tab" aria-selected={scenario===i} aria-controls="scenario-panel" onClick={()=>setScenario(i)}>{String(i+1).padStart(2,"0")} <span>{item.name}</span><span>↗</span></button>)}</div><div className="demo-content" id="scenario-panel" role="tabpanel" aria-labelledby={`scenario-${scenario}`}><div className="demo-caption"><span className="eyebrow">ILLUSTRATIVE PREVIEW</span><span className="small-tag">Read-only</span></div><h3>{s.caption}</h3><div className="demo-flow"><div><small>SOURCE</small><strong>{s.source}</strong><span>{s.change}</span></div><span className="flow-arrow">→</span><div><small>WHAT NEEDS ANOTHER LOOK</small><strong>{s.target}</strong><span className="amber-text">{s.result}</span></div></div><div className="demo-stats"><div><strong>{s.affected.toString().padStart(2,"0")}</strong><span>Related items</span></div><div><strong>{s.rules}</strong><span>Checks on those items</span></div><div><strong>0</strong><span>Results changed by this preview</span></div></div><Link to="/dashboard" className="text-link">Try it with the sample records <span>↗</span></Link></div></div></section>
      <section className="section workflow" id="how-it-works"><p className="eyebrow">BUILT AROUND THE REVIEWER</p><h2>Three steps to<br/><em>a clearer picture.</em></h2><div className="workflow-steps">{[{t:"Choose a document",d:"Pick an invoice, bank statement, accounting record, or approval note from the sample project."},{t:"See what it affects",d:"Find the items that use that document. For an invoice, try a new total and compare it with the accounting record."},{t:"Take a closer look",d:"Open a related item to see its documents and calculations, or download a report to review."}].map((s,i)=><div key={s.t}><span>0{i+1}</span><h3>{s.t}</h3><p>{s.d}</p></div>)}</div></section>
      <section className="section research" id="research"><div className="section-heading horizontal"><div><p className="eyebrow">RESEARCH → PRODUCT</p><h2>A considered extension<br/><em>of the Modus vision.</em></h2></div><p>Modus publicly emphasizes speed, audit quality, and less repetitive work. This prototype explores how those priorities extend to evidence that changes.</p></div><div className="research-grid"><a href="https://modusalliance.com/" target="_blank" rel="noreferrer"><small>01 / MODUS ALLIANCE</small><h3>Build on the existing workflow.</h3><p>Andi already supports fieldwork and scheduling. The opportunity explored here is the review impact of later evidence changes.</p><span>Product and methodology ↗</span></a><a href="https://www.linkedin.com/company/modus-audit-inc/" target="_blank" rel="noreferrer"><small>02 / COMPANY & FOUNDER POSTS</small><h3>Make judgment easier.</h3><p>The Excel assistant reinforces the importance of supporting auditors where they work and keeping review context clear.</p><span>Modus on LinkedIn ↗</span></a><a href="https://lsvp.com/stories/building-the-worlds-first-ai-native-audit-technology-our-investment-in-modus/" target="_blank" rel="noreferrer"><small>03 / LIGHTSPEED INVESTMENT THESIS</small><h3>Connect speed with quality.</h3><p>A workflow that narrows re-review effort fits the stated ambition to improve both the audit experience and its quality.</p><span>Read the investment thesis ↗</span></a></div><p className="research-note">Research-backed hypothesis, not a claim about Modus’s private roadmap. No public source reviewed established whether Modus already has this capability internally. This is an independent prototype, not an official Modus product.</p></section>
      <section className="closing-cta"><p className="eyebrow">THE EVIDENCE IS ONLY THE BEGINNING</p><h2>Find what changed.<br/><em>See what to check.</em></h2><Link className="button button-blue" to="/dashboard">Open the demo <span>↗</span></Link></section>
    </main><footer className="site-footer"><Link to="/" aria-label="Home"><Brand/></Link><p>Independent portfolio concept · 2026<br/>Made-up sample records. No connection to Modus systems.</p><a href="https://modusalliance.com/" target="_blank" rel="noreferrer">Visit Modus Alliance ↗</a></footer>
  </div>;
}
